Updated for Subrion 4.2.x
intelliants/subrion-plugin-twitter_feed pull request #3
Opened 2018-03-13 10:38 UTC by Frozenpath

Please check

2018-03-13 11:20 UTC, vbezruchkin requested changes

2018-03-13 11:20 UTC, vbezruchkin commented on docs/changelog.html
> +    <li>Version: 4.1.0
Please update version to 4.2.x

2018-03-14 03:08 UTC, Frozenpath commented on docs/changelog.html
> +    <li>Version: 4.1.0
Done

2018-03-14 04:39 UTC, vbezruchkin approved these changes

2018-03-14 04:39 UTC, merged